### PR TITLE
Calculating angles using X and Y

### PR DESCRIPTION
**Pull request by kshitijdshah99**
Here, I've replaced the display of X and Y coordinates with the calculation and display of the angle to horizontal.
Let me know if any changes required.

### CODE REVIEW

**Comment by quozl** [comment]
Commit message doesn't tell me anything about the change.  Please update.

**Comment by kshitijdshah99** [comment]
@quozl As far I understood the issue states that X and Y has not been explained properly in the code and we want to display angle to horizontal using it, am I right?
I have made changes according to my understanding, pls correct me if I am wrong

**Comment by quozl** [comment]
Sure, but if you scroll up you'll find your commit message does not explain.  "Update LevelActivity.py" says nothing.  Please fix that.  Thanks.

**Comment by kshitijdshah99** [comment]
@quozl I have made the changes you said kindly review it.

**Comment by quozl** [comment]
Thanks.  Please edit the commit message of your existing commit, and remove the two empty commits.

https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits describes what should go in a commit message; it has to stand alone, without the pull request or the issue text, because only the commit is kept by git; the pull request and issue are not part of git.

**Pull request closed without merging**
